"""Generate the SDK Custom API metadata from the reviewed server wire contract."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "server" / "process-contract.json"
OUTPUT = ROOT / "src" / "generated" / "processTrackingMetadata.ts"
INVENTORY = ROOT / "src" / "generated" / "processInventory.ts"


def render_inventory(manifest):
    seed = manifest["seed"]
    stages = seed["stages"]
    lane_names = {
        "help-flow": "Workflow orchestration", "saved-agent": "Agents / tools",
        "instrumentation-overlay": "Planned tool observation", "case-management": "Case handling",
    }
    lanes = [{"id": "email", "label": "Email channel", "order": 0}]
    for stage in stages:
        lane = "email" if stage["kind"] == "start" else stage["lane"]
        if not any(item["id"] == lane for item in lanes):
            lanes.append({"id": lane, "label": lane_names.get(lane, lane), "order": len(lanes)})
    definition = {
        "schemaVersion": 1, "definitionId": "help-email-prepared-inventory-v1",
        "code": seed["definition_code"], "name": seed["name"], "version": str(seed["version"]),
        "coverageVersion": seed["coverage_version"], "mode": "configuration",
        "description": "Prepared process definition from the inspected Help workflow. Card/default branches retain their original Failed termination; empty switch cases reach Mock_Response. Tool and case overlays are not proof of execution.",
        "lanes": lanes,
        "stages": [{
            "schemaVersion": 1, "stageCode": stage["code"], "label": stage["label"],
            "description": "Planned, uninstrumented tool boundary; no customer lookup is inferred." if stage["phase"] == "identify"
                else "Conditional lifecycle observation from explicitly linked cases." if stage["completion_authority"] == "case-observer"
                else "Observed configuration only. Successful host invocation is not proof of a financial action.",
            "laneId": "email" if stage["kind"] == "start" else stage["lane"], "phase": stage["phase"],
            "kind": stage["kind"], "order": stage["order"],
            "coverage": "uninstrumented" if stage["coverage"] == "opaque" else stage["coverage"],
            "optional": not stage["required"], "opaque": stage["coverage"] == "opaque",
            "evidence": "lifecycle" if stage["completion_authority"] == "case-observer" else "inventory",
        } for stage in stages],
        "transitions": [{
            "schemaVersion": 1, "transitionCode": edge["code"], "fromStageCode": edge["from"],
            "toStageCode": edge["to"], "label": edge["label"], "branchCode": edge["branch"],
            "optional": not edge["required"], "kind": "sequence",
        } for edge in seed["transitions"]],
        "sources": [{"name": "Prepared workflow inventory", "health": "available",
            "message": "Configuration only; the live process API must supply observed instances."}],
    }
    return "// Generated from config/process-tracking-schema.json; no runtime records.\nimport type { ProcessDefinition } from '../process/types'\nexport const PROCESS_INVENTORY: ProcessDefinition = " + json.dumps(definition, indent=2) + "\n"


def render(contract):
    api = contract["api"]
    if contract["schemaVersion"] != 1 or api["isFunction"] or api["input"] != {"name": "RequestJson", "type": "String"} or api["output"] != {"name": "ResponseJson", "type": "String"}:
        raise ValueError("Unsupported process API contract; metadata was not generated.")
    names = api["actions"]
    if len(names) != len(set(names)) or any(not name.startswith("rfd_") or not name.replace("_", "").isalnum() for name in names):
        raise ValueError("Invalid process API names.")
    data = {"processTracking": {
        "tableId": "", "version": "", "primaryKey": "", "dataSourceType": "Dataverse",
        "apis": {name: {
            "path": f"/{name}", "method": "POST",
            "parameters": [{"name": "RequestJson", "in": "body", "required": True, "type": "string"}],
            "responseInfo": {"200": {"type": "object"}},
        } for name in names},
    }}
    return "// Generated by scripts\\generate_process_bindings.py from server\\process-contract.json.\n// Validate the deployed API signatures before live release; no credentials are embedded.\nexport const processTrackingMetadata = " + json.dumps(data, indent=2) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    content = render(json.loads(CONTRACT.read_text(encoding="utf-8")))
    inventory = render_inventory(json.loads((ROOT / "config" / "process-tracking-schema.json").read_text(encoding="utf-8")))
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8", newline="\n")
        INVENTORY.write_text(inventory, encoding="utf-8", newline="\n")
    elif not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
        raise SystemExit("Process API metadata differs from the server contract; regenerate explicitly.")
    elif not INVENTORY.exists() or INVENTORY.read_text(encoding="utf-8") != inventory:
        raise SystemExit("Process inventory differs from the prepared definition; regenerate explicitly.")
    print("Process SDK metadata matches the server contract.")


if __name__ == "__main__":
    main()
